name: timelive
description: Application for viewing a company events, milestones, etc.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1

  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.11

  firebase_storage: ^10.2.13

  json_annotation: ^4.4.0

  uuid: ^3.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
